# Generated by Django 4.2.11 on 2024-04-15 13:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_employer_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='coverLetter',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.ForeignKey(default='Pending', null=True, on_delete=django.db.models.deletion.RESTRICT, to='jobs.status'),
        ),
    ]
