# Generated by Django 4.2.11 on 2024-04-16 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_coverletter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comment',
            name='recruitment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.recruitmentpost'),
        ),
        migrations.AddField(
            model_name='like',
            name='recruitment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.recruitmentpost'),
        ),
        migrations.AddField(
            model_name='rating',
            name='recruitment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.recruitmentpost'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('applicant', 'employer', 'recruitment')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('applicant', 'employer', 'recruitment')},
        ),
    ]
