# Generated by Django 4.2.11 on 2024-04-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_comment_applicant_alter_comment_employer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_student',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
