# Generated by Django 4.2.11 on 2024-04-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_comment_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
