# Generated by Django 4.2.11 on 2024-04-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_applicant_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='employmenttype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['created_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='recruitmentpost',
            options={'ordering': ['-created_date', 'id']},
        ),
        migrations.AddField(
            model_name='recruitmentpost',
            name='reported',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('employer', 'recruitment'), ('applicant', 'recruitment')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('employer', 'recruitment'), ('applicant', 'recruitment')},
        ),
    ]
