# Generated by Django 4.2.11 on 2024-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_recruitmentpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
