# Generated by Django 4.2.11 on 2024-05-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_jobapplication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentpost',
            options={'ordering': ['deadline', 'id']},
        ),
        migrations.AddField(
            model_name='recruitmentpost',
            name='saved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
