# Generated by Django 4.2.11 on 2024-05-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_recruitmentpost_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentpost',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='jobs.area'),
        ),
    ]
