# Generated by Django 4.2.11 on 2024-06-10 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_recruitmentpost_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='employer',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='areas',
            field=models.ManyToManyField(blank=True, to='jobs.area'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobs.skill'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'recruitment')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'recruitment')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='like',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='employer',
        ),
    ]
