# Generated by Django 4.2.11 on 2024-07-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_applicant',
        ),
        migrations.AlterField(
            model_name='recruitmentpost',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='jobs.area'),
        ),
        migrations.AlterField(
            model_name='recruitmentpost',
            name='employmenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.employmenttype'),
        ),
    ]
