"""
Django settings for jobPortal project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Khi dùng chat thì tắt
# DEBUG = True
DEBUG = False


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'adminlte3',
    # 'adminlte3_theme',
    # 'admin_adminlte.apps.AdminAdminlteConfig',
    # 'daphne',
    # Phần chat
    'channels',
    # Quản lý admin
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Thêm app jobs
    'jobs.apps.JobsConfig',
    'django.contrib.auth',
    # Phần để dùng trường PhoneNumberField
    'phonenumber_field',
    # Phần dùng cho Debug toolbar
    'debug_toolbar',
    # Phần CKEditor
    'ckeditor',
    'ckeditor_uploader',
    # API
    'rest_framework',
    # Phần Swagger
    'drf_yasg',
    # Phần OAuth2
    'oauth2_provider',
    # Phần filter
    'django_filters',
    'drf_spectacular',

    # Phần Docker - Tạo dữ liệu mẫu
    'scripts',
    # Phần cho đăng nhập với GG
    'social_django',
    # 'corsheaders',
    # WebSocket
    'rest_framework.authtoken',
    'dj_rest_auth',
    # Phần Redis
    'django_redis',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    'dj_rest_auth.registration',
    # Phần để kiểm tra URL
    'django_extensions',


]
# Giá trị SITE_ID = 1 thường được gán cho trang web đầu tiên mà bạn tạo
SITE_ID = 1

ASGI_APPLICATION = 'jobPortal.asgi.application'
WSGI_APPLICATION = 'jobPortal.wsgi.application'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',


]

# Link WebSocket
# https://bdvade.hashnode.dev/building-chat-apis-with-django-rest-framework-and-django-channels
CORS_ALLOW_ALL_ORIGINS = True

INTERNAL_IPS = [

    '127.0.0.1',

]

ROOT_URLCONF = 'jobPortal.urls'
MEDIA_ROOT = '%s/jobs/static' % BASE_DIR
CKEDITOR_UPLOAD_PATH = "ckeditor/images/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]






AUTH_USER_MODEL = 'jobs.User'

# Cấu hình này cho biết Django Channels sẽ sử dụng Redis làm backend cho hệ thống channel layer.
# Cấu hình CHANNEL_LAYERS sử dụng Redis làm backend cho channel layer
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Cấu hình Redis cho cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # Đường dẫn đến Redis server và database số 1
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Khi chạy DOCKER
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("redis", 6379)],
#         },
#     },
# }
#
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://redis:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # Tạo csdl mới tên là ecoursesdb
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        # Mặc định là Localhot

        # Không sử dụng Docker
        'HOST': '',

        # # Chạy trên DOCKER
        # 'HOST': 'mysql',
        # 'PORT': '3306',
    }
}

# Phần upload ảnh lên Cloudinary
import cloudinary

cloudinary.config(
    cloud_name=os.getenv('CLOUD_NAME'),
    api_key=os.getenv('CLOUD_KEY'),
    api_secret=os.getenv('CLOUD_SECRET'),

)

REST_FRAMEWORK = {
    # # Phần phân trang
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # # 'PAGE_SIZE' : Số Item trên 1 trang
    # 'PAGE_SIZE': 6,

    # Phần OAuth2
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.TokenAuthentication',  # Token Authentication
    ),

    # # Ai cũng có thể truy cập
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.AllowAny',
    # ),

    # API Schema generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Phần lọc dữ liệu
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/'
# MEDIA_URL = 'media/'
# # import os
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,  # Thời gian hết hạn của token truy cập (access token) được cấu hình là 36000 giây, tức là 10 giờ
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 600,
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
    'SCOPES': {
        'read': 'Read scope',
        'write': 'Write scope',
    },
}


# Tắt khi xin token trên Postman - bật khi đăng nhập trên app
# OAUTH2_PROVIDER = { 'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore' }
CLIENT_ID = os.environ.get('OAUTH2_ID')
CLIENT_SECRET = os.environ.get('OAUTH2_SECRET')
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND')
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')

# Đăng nhập với Google
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")
GOOGLE_TOKEN_URL = "https://www.googleapis.com/oauth2/v4/token"
GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"


# Đăng nhập với Facebook


JAZZMIN_SETTINGS = {
    # Các thiết lập chung
    "site_title": "Job Management Admin",
    "site_header": "Job Management System",
    "site_brand": "Job Management System",
    "site_logo": "images/LogoJobPortalApp.png",
    "login_logo": "images/LogoJobPortalApp.png",
    "login_logo_dark": "images/LogoJobPortalApp.png",
    "site_logo_classes": "img-circle shadow-lg",
    # icon trên thanh bookmarks
    "site_icon": "images/PersonalBrandLogo_Circle.png",
    "welcome_sign": "Welcome to Job Management System Admin Panel",
    "copyright": "  Job Management System  |  Trần Đặng Mỹ Tiên",

    # Tìm kiếm
    "search_model": [
        "jobs.User",
        # "jobs.JobApplication",
        # "recruitment.RecruitmentPost",
    ],
    "user_avatar": "avatar",

    # Menu phía trên với các liên kết quan trọng
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"], "icon": "fas fa-tachometer-alt"},
        {"name": "Basic Statistics", "url": "/myadmin/stats/", "icon": "fas fa-chart-line", "permissions": ["analytics.view_stats"]},
        {"name": "Salary Search", "url": "/myadmin/search/", "icon": "fas fa-search-dollar"},
        {"name": "Email", "url": "/myadmin/mail/", "icon": "fas fa-envelope"},
        {"name": "Job Market Stats", "url": "/myadmin/job_market_stats/", "icon": "fas fa-chart-pie"},
        {"name": "Analysis Results", "url": "/myadmin/analysis-results/", "icon": "fas fa-clipboard-list"}
    ],

    # Menu người dùng (góc trên phải)
    "usermenu_links": [
        {"name": "Profile", "url": "admin:auth_user_change", "icon": "fas fa-user-circle"},
        {"name": "Logout", "url": "admin:logout", "icon": "fas fa-sign-out-alt"},
    ],

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["sessions"],
    "hide_models": ["auth.permission"],
    "order_with_respect_to": ["auth", "job_app", "recruitment"],
    "custom_links": {
        "recruitment": [
            {
                "name": "Create Post",
                "url": "admin:recruitment_post_add",
                "icon": "fas fa-plus-circle",
                "permissions": ["recruitment.add_post"]
            },
            {
                "name": "Manage Posts",
                "url": "admin:recruitment_post_changelist",
                "icon": "fas fa-edit",
                "permissions": ["recruitment.change_post"]
            }
        ],
        "analytics": [  # Thêm một mục mới cho phân tích
            {
                "name": "View Statistics",
                "url": "/myadmin/stats/",
                "icon": "fas fa-chart-line",
                "permissions": ["analytics.view_stats"]  # Cần quyền thích hợp
            }
        ]
    },

    # Icon tuỳ chỉnh
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "job_app": "fas fa-briefcase",
        "job_app.job": "fas fa-clipboard-list",
        "recruitment": "fas fa-bullhorn",
        "recruitment.post": "fas fa-file-alt",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # Sử dụng modal'django_redis'
    "related_modal_active": True,

    # UI Tweaks
    "custom_css": "admin/custom.css",
    "custom_js": "admin/custom.js",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # Cấu hình hiển thị form
    "changeform_format": "collapsible",
    "changeform_format_overrides": {
        "auth.user": "horizontal_tabs",
        "auth.group": "vertical_tabs"
    },
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",  # Màu chủ đạo của thương hiệu
    "accent": "accent-olive",  # Màu nhấn cho các thành phần
    "navbar": "navbar-indigo navbar-dark",  # Navbar với nền tối và màu chủ đạo
    "no_navbar_border": True,  # Ẩn viền của navbar để tạo cảm giác thoáng đãng
    "navbar_fixed": True,  # Cố định navbar khi cuộn trang
    "layout_boxed": False,  # Bố cục toàn màn hình
    "footer_fixed": False,  # Footer không cố định
    "sidebar_fixed": True,  # Sidebar cố định khi cuộn trang
    "sidebar": "sidebar-dark-indigo",  # Sidebar với nền tối
    "sidebar_nav_small_text": False,  # Kích thước chữ bình thường cho menu sidebar
    "sidebar_disable_expand": True,  # Không mở rộng các mục con tự động
    "sidebar_nav_child_indent": True,  # Thụt lề cho các mục con
    "sidebar_nav_compact_style": True,  # Sử dụng kiểu compact cho sidebar
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,  # Kiểu sidebar phẳng
    "theme": "cyborg",  # Sử dụng theme tối "cyborg"
    "dark_mode_theme": "cyborg",  # Sử dụng theme tối cho dark mode
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

STRIPE_TEST_PUBLIC_KEY = os.environ.get('STRIPE_TEST_PUBLIC_KEY')
STRIPE_TEST_SECRET_KEY = os.environ.get('STRIPE_TEST_SECRET_KEY')
#
SITE_URL='http://192.168.1.56:8000'